### ISSUE TITLE
Invalid link for dataset 

### ISSUE THREAD

**Issue by Jerrywhchou** [Droid021/breast-cancer-detection#1]
Hi, in the file (Breastcancer_detection.ipynb), I find that the link of data set is invalid. (https://drive.google.com/uc?id=1r6YNGwijUHawsRHKy8qQk12FW-VQXw4p) 
I was wonder if you can update it so that I can access the dataset.

Thank you

**Comment by bx-labs** [comment]
Where to download this dataset: b_cancer_data2? The link was invalid.

Thanks,
Fan

**Comment by Dharmik1710** [comment]
Please update the link.

**Comment by mrdvince** [comment]
@Dharmik1710 @fzhang988 Haven't checked on this for a while.

Will update the whole thing soon, meantime use this dataset from kaggle.

https://www.kaggle.com/ambarish/breakhis
